<a href="https://colab.research.google.com/github/zigg17/PytorchPractice/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **00 Pytorch Fundamentals**

Textbook Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

Started: 1/5/23

Ended:

---



# **Notes:**
**3 big errors in PyTorch code:**


1.   Incorrect device
2.   Incorrect datatype
3.   Incorrect Shape

**Random numbers:**


*   `torch.randint(low= a, high= b, size= (x,y,z))` to create a tensor with random integers.
*   `torch.rand(size=(x,y,z))` to create a tensor with random float32 numbers ranging between 0 and 1.

**Range:**


*   `torch.arange(start= x, end= y, step= z)` to create a 1D tensor with a range of numbers and specefied set of steps. Remember that the bounds are inclusive at start but not inclusive at end.

**Tensor Ops:**
* Addition
* Subtraction
* Matrix multiplication
* Element-wise multiplication
* Division


**Matrix Multiplication:**
* There are two ways to perform multiplication on tensors, element-wise and matrix multiplication.
* Element wise is multiplying each element by a specefic number.
* Matrix multiplication can be considered a dot product as well multiply row of first tensor by first column and then next column and iterate through both matrices.
* `torch.matmul(1st,2nd)` will perform the matrix multiplication necessary.
* tensor @ tensor also does matrix multiplication as well.
* If theres an imbalance but the numbers of the matrices need to be flipped in order for matrix multiplication to occur, then we use `tensor.T`.

**Reproducibility**
* Reproducibility = taking the random out of random.
* Random seed, an operation that allows for "the randomness to be flavored".
* `torch.manual_seed(RANDOM_SEED)` works to flavor your tensors in PyTorch. They only work for one block of code so they must be reintroduced everytime theres another `torch.rand()` call to maintain reproducibility.
* Oh and just set `RANDOM_NUMBER = x` to create a seed to be used throughout the doc.





---





# **Tensor Creation: Ones, Zeros, and Like Tensors**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

print("We are running Pytorch version: " + torch.__version__ + "\n")

## Ones
print("Ones example:")
ones = torch.ones(4,5)
print(ones)
print("\n")

## Zeros
print("Zeros example:")
zeros = torch.zeros(2,3)
print(zeros)
print("\n")

## Random
print("Random example:")
rando = torch.rand(3,2,2)
print(rando)
print("\n")

## Tensors like
print("Ones to rand:")
randoOne = torch.rand_like(ones)
print(randoOne)
print("\n")

print("rand to ones:")
randoToOne = torch.ones_like(rando)
print(randoToOne)
print("\n")



We are running Pytorch version: 2.1.0+cu121

Ones example:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


Zeros example:
tensor([[0., 0., 0.],
        [0., 0., 0.]])


Random example:
tensor([[[0.6557, 0.0346],
         [0.1254, 0.1755]],

        [[0.9253, 0.1913],
         [0.9992, 0.2844]],

        [[0.8739, 0.6702],
         [0.6698, 0.4345]]])


Ones to rand:
tensor([[7.9437e-01, 4.9230e-02, 8.7482e-01, 6.6707e-01, 4.0600e-01],
        [6.0365e-01, 3.3777e-01, 1.6320e-01, 3.3330e-01, 9.9907e-01],
        [3.0754e-01, 9.7447e-01, 3.1942e-04, 7.5642e-01, 7.3056e-01],
        [7.3854e-01, 7.3579e-01, 8.3781e-01, 8.1873e-01, 5.1648e-01]])


rand to ones:
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])




# **Tensor Creation: Ranged Tensors, Data Type, and Device**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

print("We are running Pytorch version: " + torch.__version__ + "\n")

## For creating a tensor of random integers within a specified range
print("Random int creation:")
tensorInt = torch.randint(low=0, high= 1000, size= (2,3,3))
print(tensorInt.dtype)
print("\n")
print(tensorInt)
print("\n")

## For creating a stepping basis for tensors
print("Range creation:")
step = torch.arange(start= 0, end= 21, step= 5)
print(step)
print("\n")

## Playing around
print("Multiplication:")
tensorInt2 = torch.randint(low= 0, high= 1000, size= (2,3,3))
tensorInt3 = tensorInt * tensorInt2
print(tensorInt3)
print("\n")

## Device alteratation
print("GPU tensor:")
gpuTensor = torch.rand(size= (3,3,2), device= 'cuda')
print(gpuTensor)

We are running Pytorch version: 2.1.0+cu121

Random int creation:
torch.int64


tensor([[[175, 952, 579],
         [322, 303, 828],
         [845, 846, 784]],

        [[816, 215, 363],
         [733, 692, 722],
         [716, 373, 952]]])


Range creation:
tensor([ 0,  5, 10, 15, 20])


Multiplication:
tensor([[[ 72975, 758744,  11001],
         [129444, 159378, 510048],
         [654030, 364626, 227360]],

        [[146064,  25370,  68607],
         [362835, 489244, 697452],
         [692372, 261100, 931056]]])


GPU tensor:
tensor([[[0.0759, 0.1828],
         [0.0707, 0.2284],
         [0.5194, 0.5232]],

        [[0.2544, 0.4215],
         [0.2728, 0.7128],
         [0.9181, 0.9457]],

        [[0.6733, 0.3586],
         [0.4047, 0.4210],
         [0.5171, 0.9573]]], device='cuda:0')
1 CUDA device(s) available.
Device 0: Tesla T4


# **Tensor Ops: Addition, Scalar Multiplication, and Element-wise Multiplication**


---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

## Creation
print("Original:")
tensor = torch.randint(size= (2,2,3), device= 'cuda', low= 1, high= 10)
print(tensor)
print("\n")

## Addition
print("Addition plus 1:")
tensorAdd = tensor + 1
print(tensorAdd)
print("\n")

## Scalar multiplication
print("Multiplication times 2:")
tensorMult = tensor * 2
print(tensorMult)
print("\n")

## Element multiplication
print("Multiplication of two tensors:")
tensorSquare = tensor * tensor
print(tensorSquare)
print("\n")

Original:
tensor([[[7, 6, 5],
         [3, 4, 2]],

        [[3, 8, 7],
         [8, 4, 9]]], device='cuda:0')


Addition plus 1:
tensor([[[ 8,  7,  6],
         [ 4,  5,  3]],

        [[ 4,  9,  8],
         [ 9,  5, 10]]], device='cuda:0')


Multiplication times 2:
tensor([[[14, 12, 10],
         [ 6,  8,  4]],

        [[ 6, 16, 14],
         [16,  8, 18]]], device='cuda:0')


Multiplication of two tensors:
tensor([[[49, 36, 25],
         [ 9, 16,  4]],

        [[ 9, 64, 49],
         [64, 16, 81]]], device='cuda:0')




# **Tensor Ops: Matrix Multiplication and Transpostion**


---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

print("We are running Pytorch version: " + torch.__version__ + "\n")

print("3x2:")
tensor1 = torch.rand(size= (3,2))
print(tensor1)
print("\n")

print("3x2, 2:")
tensor2 = torch.rand(size= (3,2))
print(tensor2)
print("\n")

## .T flips the tensors dimensions
print("3x2, 2, transposed:")
tensor2 = tensor2.T
print(tensor2)
print("\n")
print("Essentially flip the tensor 90 degrees clockwise.")
print("\n")

tensorFinal = torch.matmul(tensor1,tensor2)
print("Matrix multiplication 3x2 and 2x3:")
print(tensorFinal)




We are running Pytorch version: 2.1.0+cu121

3x2:
tensor([[0.7200, 0.7450],
        [0.2069, 0.5289],
        [0.5482, 0.7395]])


3x2, 2:
tensor([[0.8343, 0.5153],
        [0.6467, 0.4505],
        [0.2080, 0.0444]])


3x2, 2, transposed:
tensor([[0.8343, 0.6467, 0.2080],
        [0.5153, 0.4505, 0.0444]])


Essentially flip the tensor 90 degrees clockwise.


Matrix multiplication 3x2 and 2x3:
tensor([[0.9845, 0.8012, 0.1829],
        [0.4451, 0.3720, 0.0665],
        [0.8384, 0.6877, 0.1469]])


# **Tensor Ops: Mean, Sum, Min, Max**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

print("We are running Pytorch version: " + torch.__version__ + "\n")

tensor = torch.rand(size= (3,3))
print("Tensor:")
print(tensor)
print("\n")

print("Max element:")
print(tensor.max())
print("\n")

print("Min element:")
print(tensor.min())
print("\n")

print("Mean:")
print(tensor.mean())
print("\n")

print("Sum:")
print(tensor.sum())
print("\n")

print("All of these return an important value, and its always a single element.")

We are running Pytorch version: 2.1.0+cu121

Tensor:
tensor([[0.6566, 0.0494, 0.1148],
        [0.6809, 0.5548, 0.2198],
        [0.7153, 0.8874, 0.5844]])


Max element:
tensor(0.8874)


Min element:
tensor(0.0494)


Mean:
tensor(0.4959)


Sum:
tensor(4.4635)


All of these return an important value, and its always a single element


# **Tensor Ops: Argmin, Argmax**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

tensor = torch.rand(3,4)
print("Tensor:")
print(tensor)
print("\n")

print("Index of smallest:")
print(tensor.argmin())
print("\n")

print("Index of largest:")
print(tensor.argmax())
print("\n")

Tensor:
tensor([[0.5672, 0.1285, 0.6291, 0.5951],
        [0.2599, 0.8713, 0.6343, 0.7837],
        [0.5994, 0.0837, 0.9192, 0.8588]])


Index of smallest:
tensor(9)


Index of largest:
tensor(10)




# **Tensor Ops: Reshaping, View, and Stacking**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

tensor = torch.arange(start=0, end= 11, step= 1)
print("Intial tensor:")
print(tensor)
print("\n")

print("Reshaped tensor:")
print(tensor.reshape(11,1))
print("\n")

## I have no idea what the fuck is going on with view other than it
## creates a new variable. That shares the same mem space? Like wat?
## I just need to look into documentation and further examples

## dim= 1 alters the way things concatenate, it flips them to vertical and
## concatenates them horizontally, dim= 0 keeps the original stack and
## stacks vertically
stacked = torch.stack([tensor, tensor], dim= 0)
print("Stacked tensor (based off of initial):")
print(stacked)

Intial tensor:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Reshaped tensor:
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])


Stacked tensor (based off of initial):
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])


# **Tensor Ops: Squeezing and Unsqueezing**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

tensor = torch.rand(3,1)
print("Presqueeze:")
print(tensor)
print("\n")

tensor = tensor.squeeze()
print("Postsqueeze:")
print(tensor)
print("\n")

for i in range(3):
  tensor = tensor.unsqueeze(dim= 1)
print("Resqueeze: 3 times vertically:")
print(tensor)
print("\n")

Presqueeze:
tensor([[0.1575],
        [0.5267],
        [0.6593]])


Postsqueeze:
tensor([0.1575, 0.5267, 0.6593])


Resqueeze:
tensor([[[[0.1575]]],


        [[[0.5267]]],


        [[[0.6593]]]])




# **Tensor Ops: Permuting and Indexing**


---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

tensor = torch.rand(3,2,2)
print("Orig tensor:")
print(tensor)
print(tensor.shape)
print("\n")

tensor1 = tensor.permute(2,0,1)
print("Permuted tensor:")
print(tensor1)
print(tensor1.shape)
print("\n")

manip = torch.arange(1,10).reshape(1,3,3)
print(manip)
print("\n")
print(f"[0][0] = {manip[0][0]}, [0][0][0] = {manip[0][0][0]}")
print("\n")
print(f"Accessing 9: {manip[0][2][2]}, Accessing column: {manip[:, :, 2]}")
## Swith to full brackets with commas as it allows for the incorporation
## of semi-colons, maybe use multi squares for iterations

Orig tensor:
tensor([[[0.5551, 0.3308],
         [0.8562, 0.8448]],

        [[0.8906, 0.3898],
         [0.3239, 0.5547]],

        [[0.0058, 0.3371],
         [0.0835, 0.9432]]])
torch.Size([3, 2, 2])


Permuted tensor:
tensor([[[0.5551, 0.8562],
         [0.8906, 0.3239],
         [0.0058, 0.0835]],

        [[0.3308, 0.8448],
         [0.3898, 0.5547],
         [0.3371, 0.9432]]])
torch.Size([2, 3, 2])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


[0][0] = tensor([1, 2, 3]), [0][0][0] = 1


Accessing 9: 9, Accerssing row: tensor([[3, 6, 9]])


# **Tensor Ops: To and From NumPy**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

print("Numpy to PyTorch:")
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(tensor)
print("\n")
print(tensor.dtype)
print("\n")

print("Pytorch to NumPy:")
tensor = torch.ones(7)
numpyTensor = tensor.numpy()
print(numpyTensor)
print("\n")
print(numpyTensor.dtype)

Numpy to PyTorch:
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


torch.float64


Pytorch to NumPy:
[1. 1. 1. 1. 1. 1. 1.]


float32


# **Tensor Reproducibility:**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

RANDOM_SEED = 69

torch.manual_seed(RANDOM_SEED)
brother = torch.rand(2,3)

torch.manual_seed(RANDOM_SEED)
brother1 = torch.rand(2,3)

print(brother)
print(brother1)
print(brother == brother1)
print("\nAYOOOO")

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])
tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])
tensor([[True, True, True],
        [True, True, True]])

AYOOOO


# **Accessing the GPU**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor = torch.rand(3,2)
print(tensor.device)
gpuTensor = tensor.to(device)
print(gpuTensor.device)


cpu
cuda:0


# **Trash Throwaway**

---



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

tensor = torch.rand(3,2,2)
permutation = tensor.permute(2,0,1)
print(tensor)
print("\n")
print(permutation)
print("\n")

tensor[0,0,0] = 69420
print(tensor)
print("\n")
print(permutation)
print("\n")

tensor([[[0.2330, 0.4851],
         [0.3645, 0.6096]],

        [[0.5281, 0.8748],
         [0.3867, 0.0591]],

        [[0.3284, 0.2940],
         [0.4924, 0.2687]]])


tensor([[[0.2330, 0.3645],
         [0.5281, 0.3867],
         [0.3284, 0.4924]],

        [[0.4851, 0.6096],
         [0.8748, 0.0591],
         [0.2940, 0.2687]]])


tensor([[[6.9420e+04, 4.8510e-01],
         [3.6455e-01, 6.0964e-01]],

        [[5.2806e-01, 8.7478e-01],
         [3.8665e-01, 5.9135e-02]],

        [[3.2836e-01, 2.9402e-01],
         [4.9239e-01, 2.6872e-01]]])


tensor([[[6.9420e+04, 3.6455e-01],
         [5.2806e-01, 3.8665e-01],
         [3.2836e-01, 4.9239e-01]],

        [[4.8510e-01, 6.0964e-01],
         [8.7478e-01, 5.9135e-02],
         [2.9402e-01, 2.6872e-01]]])


