<a href="https://colab.research.google.com/github/zigg17/pytorchPractice/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch

tensor = torch.rand(7,7)
print(tensor)
print(tensor.shape)

tensor([[0.6278, 0.7644, 0.8343, 0.3399, 0.3240, 0.9047, 0.9575],
        [0.4418, 0.5201, 0.3153, 0.7849, 0.8952, 0.9209, 0.4627],
        [0.5043, 0.6444, 0.8181, 0.7520, 0.7485, 0.7767, 0.5208],
        [0.8816, 0.6443, 0.4762, 0.5755, 0.0127, 0.9819, 0.2137],
        [0.7293, 0.8267, 0.5342, 0.2783, 0.6198, 0.4100, 0.8063],
        [0.2041, 0.1379, 0.8537, 0.0385, 0.0401, 0.7104, 0.4000],
        [0.0354, 0.7949, 0.7959, 0.2358, 0.1791, 0.8144, 0.4761]])
torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
tensor1 = torch.rand(1,7)
tensor1 = tensor1.T

finalTensor = torch.matmul(tensor,tensor1)

print(finalTensor)


tensor([[2.2757],
        [3.2116],
        [2.0681],
        [2.0345],
        [2.2707],
        [2.3948],
        [0.9561]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(7,7)
tensor3 = torch.rand(1,7)
tensor3 = tensor3.T

# Matrix multiply tensors
finalTensor1 = torch.matmul(tensor2, tensor3)
print(finalTensor1)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Create two random tensors on GPU
tensor4 = torch.rand(size= (2,3))
tensor5 = tensor4.to(device)

tensor6 = torch.rand(size= (2,3))
tensor7 = tensor6.to(device)

print(f"Device: {device}")
tensor5, tensor7

Device: cuda:0


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
tensor8 = torch.matmul(tensor5, tensor7.T)
tensor8

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
maxTensor = torch.max(tensor8)

# Find min
minTensor = torch.min(tensor8)

maxTensor, minTensor

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
argMaxTensor = torch.argmax(tensor8)

# Find arg min
argMinTensor = torch.argmin(tensor8)

argMaxTensor, argMinTensor

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor
final = torch.rand(size= (1,1,1,10))

# Remove single dimensions
final1 = torch.squeeze(final)

# Print out tensors and their shapes
final, final.shape, final1, final1.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))